//! Parameter tables for effect blocks.
//!
//! Every block's settings are a plain struct of `f32` fields generated by
//! [`params!`]. That gives, for free and consistently across all blocks:
//! serde (JSON presets; missing fields take their defaults), a static table of
//! [`ParamDef`]s for the UI (name, range, default, unit, one-line doc), and
//! index-based get/set so the audio thread can change a parameter without
//! string handling or allocation. Values are clamped to their range on set.

use serde::Serialize;

/// Description of one parameter, for building sliders.
#[derive(Debug, Clone, Copy, Serialize)]
pub struct ParamDef {
    /// Field name as used in JSON and `set_param` (e.g. "pitch_st").
    pub name: &'static str,
    pub min: f32,
    pub max: f32,
    pub default: f32,
    /// Unit shown next to the value: "dB", "Hz", "ms", "st" (semitones), "x" (ratio), "" (0..1 amount), "s".
    pub unit: &'static str,
    /// One-line description.
    pub doc: &'static str,
}

/// Defines a parameter struct. Syntax per field:
/// `/// doc` `name: [min, max, default, "unit"],`
macro_rules! params {
    (
        $(#[$m:meta])*
        pub struct $S:ident {
            $(
                $(#[doc = $doc:literal])*
                $f:ident : [$min:expr, $max:expr, $def:expr, $unit:literal]
            ),* $(,)?
        }
    ) => {
        $(#[$m])*
        #[derive(Debug, Clone, Copy, PartialEq, serde::Serialize, serde::Deserialize)]
        #[serde(default)]
        pub struct $S {
            $( $(#[doc = $doc])* pub $f: f32, )*
        }

        impl Default for $S {
            fn default() -> Self {
                Self { $( $f: $def as f32, )* }
            }
        }

        impl $S {
            /// Parameter table, in field order (the index used by `get`/`set`).
            pub const PARAMS: &'static [$crate::voice::params::ParamDef] = &[
                $( $crate::voice::params::ParamDef {
                    name: stringify!($f),
                    min: $min as f32,
                    max: $max as f32,
                    default: $def as f32,
                    unit: $unit,
                    doc: concat!("" $(, $doc)*),
                }, )*
            ];

            /// Value of parameter `i` (see `PARAMS`).
            #[allow(unused_assignments, unused_mut)]
            pub fn get(&self, i: usize) -> Option<f32> {
                let mut k = 0usize;
                $( if i == k { return Some(self.$f); } k += 1; )*
                None
            }

            /// Set parameter `i`, clamped to its range. Returns false for an unknown index
            /// or a non-finite value.
            #[allow(unused_assignments, unused_mut)]
            pub fn set(&mut self, i: usize, v: f32) -> bool {
                if !v.is_finite() { return false; }
                let mut k = 0usize;
                $( if i == k { self.$f = v.clamp($min as f32, $max as f32); return true; } k += 1; )*
                false
            }

            /// Clamp every field into its range (after deserialising user JSON).
            #[allow(dead_code)]
            pub fn sanitize(&mut self) {
                $( if !self.$f.is_finite() { self.$f = $def as f32; }
                   self.$f = self.$f.clamp($min as f32, $max as f32); )*
            }
        }
    };
}
pub(crate) use params;

/// Index of `name` in a parameter table.
pub fn index_of(table: &[ParamDef], name: &str) -> Option<usize> {
    table.iter().position(|p| p.name.eq_ignore_ascii_case(name))
}

#[cfg(test)]
mod tests {
    params! {
        /// Test struct.
        pub struct T {
            /// Alpha.
            a: [0.0, 1.0, 0.5, ""],
            /// Beta in dB.
            b: [-10.0, 10.0, 0.0, "dB"],
        }
    }

    #[test]
    fn table_get_set_clamp_serde() {
        let mut t = T::default();
        assert_eq!(T::PARAMS.len(), 2);
        assert_eq!(T::PARAMS[1].name, "b");
        assert_eq!(T::PARAMS[1].doc, " Beta in dB.");
        assert!(t.set(1, 50.0));
        assert_eq!(t.get(1), Some(10.0));
        assert!(!t.set(2, 1.0));
        assert!(!t.set(0, f32::NAN));
        let j: T = serde_json::from_str(r#"{"b": -3}"#).unwrap();
        assert_eq!(j.a, 0.5);
        assert_eq!(j.b, -3.0);
        assert_eq!(super::index_of(T::PARAMS, "B"), Some(1));
    }
}
